language: python

python: 3.5

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35

install: pip install tox

script: tox

matrix:
  include:
    - script: bin/check_for_differences
      env:
        - SUITE=Source

notifications:
  email: false
